import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            backgroundColor: "teal",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: "100%",
            fontSize: "25px",
            padding: "5px",
          }}>
          <Link href={"/"} style={{ margin: "0 7px" }}>
            {" "}
            Home{" "}
          </Link>
          <Link href={"/posts"} style={{ margin: "0 7px" }}>
            {" "}
            posts{" "}
          </Link>
          <Link href={"/articles"} style={{ margin: "0 7px" }}>
            {" "}
            Articles{" "}
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
